### ISSUE TITLE
Weekly Filename Registering Off By One

### ISSUE THREAD

**Issue by jlcala** [liamcain/obsidian-calendar-plugin#100]
When I have the locale as en-GB and the filename format as YYYY-WW, the weeks are registering off by one. For example, week 1 is  showing as a pip under week 2. When I change the file format to YYYY-ww, the weeks and filenames line up correctly.

**Comment by liamcain** [comment]
The numbering on the calendar itself is all based on the locale, so it makes sense that there is a mismatch. You should definitely be using `ww` for week numbers (even if the locale is en-GB) just so that things stay in sync.

Also, separate note: You should use `gggg` instead of `YYYY` though for the year, otherwise you could run into issues where a week spans multiple years.

So stick with `gggg-ww`. I'll see about adding a warning to the settings so that others don't try to use `WW`.
