### ISSUE TITLE
1.4.13 (and all subsequent) stopped working with my note layout

### ISSUE THREAD

**Issue by pjeby** [liamcain/obsidian-calendar-plugin#125]
### Describe the bug

My daily notes folder pattern is `YYYY/MM/YYYY-MM-DD \C\A\L\L` -- that is, e.g. `2021/01/2021-01-29 CALL.md` would be today's note.  This pattern worked fine with this plugin up to and including version 1.4.12.  1.4.13 and above refuse to acknowledge that my (5 years worth of) daily notes exist.

### Steps to reproduce

1. Configure the plugin with the date format shown (or any format that includes a `/`
2. Create a note with the correct path, and enough content that a dot should display
3. The calendar plugin does not display a dot, even if you use the calendar plugin to create the note
4. Clicking on the date of the created note will say it doesn't exist and ask to create it (which will then fail since it does in fact exist)

### Expected behavior

It should detect existing notes according to the format, displaying dots and opening the files instead of trying to create them again.

#### OS

Windows

#### Obsidian Version (e.g. v0.10.6)

0.10.11

### Theme (if applicable):

Not applicable

**Comment by liamcain** [comment]
Hi @pjeby, sorry to here it's not working for you. The plugin doesn't support nested directories for the daily notes format. If it did in a previous version, that wasn't intentional.

I recommend you update your Daily Note settings to the following:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/693981/106344250-62042080-6277-11eb-9d88-2e63f3058037.png">

**Date Format:** `YYYY-MM-DD [CALL]`
**New file location**: `<empty>`

> A couple of notes here: 
> - [CALL] in brackets is how moment.js escapes characters.
> - By leaving the folder location empty, the calendar plugin will recursively search your vault for any files matching the file format. This is likely your best option since the daily notes folder format doesn't expect Moment.js format strings.

This should let the calendar find the files again, and it will be compatible with the core Daily Notes plugin so you'll be able to use those features as well. The downside to this is that creating new files won't show up in the nested location automatically. You'll have to move them yourself. This will continue to be an issue until the Daily Notes plugin supports the nested paths.

Sorry for any inconvenience!

There is a relevant discussion around nested directories [here](https://github.com/liamcain/obsidian-calendar-plugin/discussions/21).

**Comment by pjeby** [comment]
Hi Liam.  The change to support this is pretty straightforward, specifically, instead of calling moment in several places in the daily note plugin, use this:

```js
fileDate(file) {
    const format = this.getFormat();
    let basename = file.basename;
    if (format.contains("/")) {
        const numParts = format.split("/").length;
        basename = file.path.split("/").slice(-numParts).join("/");
        if (file.extension) {
            basename = basename.slice(0, -(1+file.extension.length));
        }
    }
    const moment = window.moment(basename, format, true);
    return moment.isValid() ? moment : null;
}
```

This will correctly handle slashed date format.   I haven't implemented a full hotfix yet, but I've tested that the above code works for various /-separated format strings, and you should be able to verify by inspection that if there is no / in the format, it should work the same as the existing, inline file-to-date conversions in `.iterateDailyNotes()` and `.getCurrentFileDateTimestamp()`.  If those are also what the calendar plugin is using, I believe it should restore the functionality.

**Comment by liamcain** [comment]
Hi, I understand the changes needed. However, because I'm leveraging the daily-notes plugin for these settings, I would like to maintain compatibility with the Daily Notes core featureset. Adding something like this would change the meaning of the Daily Notes settings and will result in broken functionality for users who then try to use Daily Notes plugin features. This applies to the `Open Today Note` palette command, the ribbon button, and the next/previous daily note commands which don't currently support `/`s in the format.

**Comment by pjeby** [comment]
I'm not sure I follow you -- the only core functionality actually broken in the core plugin is the go next/previous commands, but they have been broken all along, so I'm not clear on how changing the plugin will break the core.

My goal here is just to avoid needing to fork and build the calendar plugin to fix this, since it would basically be bundling a patched version of `obsidian-daily-notes-interface`...  which I can't fork directly because there's no public repo.  So no matter what I end up doing some kind of hand-editing to maintain this.

**Comment by pjeby** [comment]
Ok, I *think* I get you now...  from my perspective, I see the Daily Notes plugin as "working" because with the format I'm using, it creates files in the right place.  From yours, the Daily Notes plugin is "working" with a pure-basename format, it just creates in the wrong folder.

I also went and re-read that discussion, to understand others' workflows, and I have an idea that can make *both* work, so that Daily Notes won't be "broken", but my workflow would still work:

```js
function getDateFromFile(file) {
    const format = getDailyNoteSettings().format.split("/").pop();
    const noteDate = window.moment(file.basename, format, true);
    return noteDate.isValid() ? noteDate : null;
}
```

If I understand your objection correctly, this would not affect the people with subfolders who move their notes after the month is over, but would still allow me to have the Daily Notes plugin create the notes there in the first place.  While there are two methods in the Daily Notes plugin that would need the same fix, the result would be enough flexibility for all the requested workflows with no breakage.  It *does* require that the format always include the full date in the basename, but that's fine for my use case and apparently everyone else's as well.

Have I understood correctly now what the issue was?

**Comment by liamcain** [comment]
> the only core functionality actually broken in the core plugin is the go next/previous commands

Another piece of it is that "Open Today's Note" won't create nested folders if they don't exist. Is this something you're currently doing manually? It does seem to navigate correctly to the note once it exists, which I didn't expect.

> Ok, I _think_ I get you now... from my perspective, I see the Daily Notes plugin as "working" because with the format I'm using, it creates files in the right place. From yours, the Daily Notes plugin is "working" with a pure-basename format, it just creates in the wrong folder.

That's part of it, but the main thing is that it overloads the meaning of the Daily Note settings. It means "format" no longer just matches the basename, but instead defines the New File Location. The Daily Notes `folder` setting is currently labeled "New File Location" which in my mind is already super confusing. If I could update the SettingsTab for the daily notes plugin and clear up that ambiguity, there'd be no objections from me. But since there is already an assumption that format = basename, New File Location = root folder, I don't want to encourage breaking those definitions.

One approach I could see is adding a "Daily Notes-compatibility" switch to the Calendar settings which would at least show users that there is a trade-off upfront. When disabled I could even display my own settings with less ambiguous language. This raises additional concerns though since the Calendar isn't the only plugin that relies on the Daily Note settings. Anyway, I need to give it some more thought. Until then, if it's easier for you, here's the repo for the daily-notes-interface if you'd like to fork it: https://github.com/liamcain/obsidian-daily-notes-interface

I'll also reach out to the Obsidian devs to see if your use case is something they would like to support in the Daily Notes plugin and propose some updated language.

**Comment by pjeby** [comment]
My folders are currently being created by cron job, though I do hope that someday the vault API will just make the directories when you create a file.

As for overloading the meaning of the Daily Notes setting I'm still having trouble understanding, since if the Daily Notes setting doesn't support anything but a basename, then Calendar dropping everything *but* the basename when comparing files would just be consistent with that, no?

(I would just change the daily notes creation location each month, but then this plugin would only find notes for the current month. In addition, the Review plugin wouldn't create files in the right location for future dates.)

As for the use case, [this thread](https://forum.obsidian.md/t/daily-notes-plugin-allow-folder-in-note-name/413/2) is one of the earlier discussions, which appears to indicate that they are at least for the moment not planning to *disallow* slashes in the format, just that they are not officially providing any support for it.

So if you could both agree on "allow full path for create, but use the base for extracting dates from files", that'd be awesome, as it would still support folks who move their files after the month is up, but also the creation for folks like me.  (There appear to be several outstanding feature requests for Obsidian to create folders on-demand, as well, so perhaps eventually I'll be able to drop my cron job as well.)

In the meantime, thank you for publishing the repo so I can fork!



.

**Comment by liamcain** [comment]
Okay, so I've given this more thought and here's what I ended up with:

- `obsidian-daily-notes-interface` now handles nested directories in the "format"
- `obsidian-daily-notes-interface` now also recursively creates nested folders as needed
- I created a new plugin called [Periodic Notes](https://github.com/liamcain/obsidian-periodic-notes) which adds support for nested directories within the Daily Notes commands (e.g. Open Today)
  - This also enabled me to add better validation and error handling within the settings, hopefully avoiding potential confusion as to where notes will appear.

I'll release a new version of the calendar plugin with support for the above after I finish up QA.

**Comment by pjeby** [comment]
That is excellent news!  It sounds like I can just drop Obsidian's daily notes and use Periodic Notes instead, yes?

**Comment by liamcain** [comment]
@pjeby yeah, exactly. There is a wizard in the Periodic Notes settings that migrates your settings over too.

**Comment by pjeby** [comment]
I tried it out, looks nice!  There is a minor error: the "previous" command doesn't say "previous" in its name.  But it works great.

Turns out I can't actually deactivate the daily notes plugin since the Review plugin still depends on it.  But it looks like I'll be able to get rid of the cron job.  And if the review plugin switches over to using daily notes interface I won't even have to create my monthly folders in advance.  And the idea of having monthly notes actually seems really useful.

Thanks for all your work on this!

**Comment by liamcain** [comment]
>  There is a minor error: the "previous" command doesn't say "previous" in its name

Oh good catch, will make a fix for that!

>  And if the review plugin switches over to using daily notes interface I won't even have to create my monthly folders in advance

Yeah, I think that's been on the back-burner for Ryan for a while, will see if he needs any help porting over it over to the interface.

**Comment by jugglingjsons** [comment]
I just wanted to to say that the amount of dedication you give to the tools you create & the community of feature hungry users is AMAZING. I initially went on the hunt through the interface repo, just to realise my folder structure should just work.
Thanks for making the internet (and Obsidian) such a great place!
