### ISSUE TITLE
Date-1 and Date+1 did not Convert on Create Daily Note

### ISSUE THREAD

**Issue by ddetton** [liamcain/obsidian-calendar-plugin#168]
> running 1.5.10
### Describe the bug
Date+1 and Date-1 did not convert when I created Daily Note after midnight.  Here is my Daily Note in Edit

---
aliases: Apr 5 2021
tags: type/daily-note
---
[[{{date-1d:YYYY-MM-DD}}]]	<-	Today	->	[[{{date+1d:YYYY-MM-DD}}]]

# Daily Note for Monday, April 5, 2021
## Random Quote
> The best way to predict the future is to create it.
> &mdash; <cite>Abraham Lincoln</cite>

## Review

Herre is my Daily Note in Preview

{{date-1d:YYYY-MM-DD}} <- Today -> {{date+1d:YYYY-MM-DD}}

Daily Note for Monday, April 5, 2021
Random Quote
 The best way to predict the future is to create it.
— Abraham Lincoln
Tasks
Review
_A clear and concise description of what the bug is._

### Steps to reproduce

1. Clicked on Open Daily Note after midnight.

### Expected behavior

_Expected it to correcly calculate Date-1 and Date+1
### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment (please specify)
Windows 10 Pro - 

#### OS
Windows 10 Pro
 
[Windows/macOS/Linux]

#### Obsidian Version (e.g. v0.10.6)
0.11.5

`(Settings → About → Current Version)`

### Theme (if applicable):
Reverie

_If the bug is visual, please provide the name of the Community Theme you're using._

**Comment by ddetton** [comment]
If I click today's date on the calendar, the dates are calculated correctly.  However, if I click the "Open today's daily note" in the sidebar, it does not convert the dates.

**Comment by liamcain** [comment]
Hi @ddetton, that's expected since `Open today's daily note` is a button controlled by the core Daily Notes plugin rather than the calendar. The core daily note plugin doesn't support the date calculations, so that explains the discrepancy in the behavior. Sorry about that, I should make that more clear in the README!

There are a few options though. The `Templater` plugin can perform the same calculations and also works with the Daily Notes plugin. Or you could use the `Periodic Notes` plugin that replaces the core Daily Notes plugin and adds additional features such as date calculations.

**Comment by ddetton** [comment]
The Periodic Notes plugin is perfect!  Thank you @liamcain !  Closing issue.
