### ISSUE TITLE
Year navigation

### ISSUE THREAD

**Issue by trijste** [liamcain/obsidian-calendar-plugin#225]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The feature might have already been included 😄

up-to-date

**Is your feature request related to a problem? Please describe.**

I'm trying to backfill an old online diary into obsidian and match the date stamps from the past with daily notes. In the plugin, I can only go back one month at a time, and I'm trying to go back twenty years.

**Describe the solution you'd like**

I want to click on the year and input the desired year to go back to it, or else some other way to navigate to a specific month and year.

**Describe alternatives you've considered**

There might be a way to do this outside of the calendar plugin by editing some hidden code to set a date for the daily note, but I haven't yet learned of it.

**Additional context**

none

**Comment by trijste** [comment]
Well, in checking back at my database I see now that the notes aren't appearing in the calendar. I moved them out of my daily notes folder and into their own folder specific to the archiving project, which seemingly removes them from the calendar. I'm not sure I can get to what I'm looking for at the moment...

**Comment by oldjove** [comment]
The Obsidian 42 - Jump to Date plugin can help with the first issue. https://github.com/TfTHacker/obsidian42-jump-to-date  Once you "arrive" you can use Calendar's "reveal active note" command to show the correct month in the calendar.

On the other issue, how are you structuring your archive? Are the archive folders subfolders of your daily notes folder?

**Comment by trijste** [comment]
@oldjove thank you for this. I think it's my structure. I have daily notes in a folder within my vault. I'm collecting notes and ramblings from different platforms and incorporating them into my vault. I decided to create folders to contain the specific notes from these platforms, but in doing so I've removed those notes from the daily notes folder and seemingly therefore the calendar? 

Ideally, the calendar might disentangle from daily notes and there would be some way of stamping a meta time tag to anchor the note within my personal chronology. I'd like to evenutally recapitulate the goings on in my life at certain times in the past (10 or more years ago), like I will be able to do moving forward with the daily notes.

**Comment by oldjove** [comment]
@trijste no worries. A couple of thoughts on this -- not sure if they're helpful. What _I_ do is assign a date format in Daily Notes as follows: YYYY/YYYY-MM/YYYY-MM-DD -- so every daily note is automatically created in folders for the appropriate year and month. If the folder doesn't yet exist, this will create it. This makes all the notes much easier to manage, especially because mine go back many years. If I want to link other non-daily notes to particular dates, I just enter the relevant date as a link. This can be easily achieved using the Natural Language Dates plugin. You just hit the shortcut key (default is @) and then type the relevant date in, duh, natural language. Then on the date in question you can look at the backlinks to see all the notes referring to it.

Another thought: if you want to track where notes and ramblings have come from, why not use tags rather than folders?

**Comment by trijste** [comment]
@oldjove Thanks again! I've converted to your style. I am using tags as well, but am still developing some methodology to keep it organized. Appreciate you writing here. I'm closing this issue :)

**Comment by oldjove** [comment]
You're very welcome!
