### ISSUE TITLE
Plugin broken in Obsidian version 0.15.0

### ISSUE THREAD

**Issue by erikwestra** [liamcain/obsidian-calendar-plugin#253]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The bug might have already been fixed 😄

### Describe the bug

In version 0.15.0 of Obsidian, released today, the way links are opened from within a sidebar has changed.  Instead of opening the link in the main pane, it now opens the link in the sidebar.

Unfortunately, this affects the calendar plugin -- clicking on a date now replaces the calendar widget with the daily note.  And because the sidebar is narrow, the daily note is opened in far too narrow a pane, making it very hard to read.

### Steps to reproduce

1. Make sure you're using Obsidian version 0.15.0 with the Calendar plugin installed.
2. Show the calendar in the right sidebar
3. Click on a date in the calendar with an existing daily note.
4. See that the daily note is opened in the right sidebar, replacing the calendar view.

### Expected behavior

The Calendar plugin should open the daily note in the centre panel rather than in the right sidebar.

### Screenshots

n/a

### Environment (please specify)

n/a

#### OS

Mac OS X.

#### Obsidian Version (e.g. v0.10.6)

0.15.0

### Theme (if applicable):

n/a

**Comment by lujun723** [comment]
same question

**Comment by Missionary2112** [comment]
Yeah I ran into same issue. The only solution is to click on the main editor to switch the focus there, then click on the date in Calendar Plug-in for it to work.

**Comment by billpetro** [comment]
Ditto. I noticed the same behavior.

**Comment by oldjove** [comment]
Yup, same for me.

**Comment by I-Pch** [comment]
Same here 😔 !

I couldn't find a way to go around this new buggy behavior 😞 ...

**Comment by I-Pch** [comment]
> Yeah I ran into same issue. The only solution is to click on the main editor to switch the focus there, then click on the date in Calendar Plug-in for it to work.

That works for switching between existing daily notes ... Not creating new ones (from what I can see) 😞

**Comment by I-Pch** [comment]
> Yeah I ran into same issue. The only solution is to click on the main editor to switch the focus there, then click on the date in Calendar Plug-in for it to work.

That works for switching between existing daily notes ... Not creating new ones (from what I can see) 😞

**Comment by liamcain** [comment]
Thanks for the report! This will be fixed by Obsidian in the upcoming 0.15.1 version.

**Comment by OogieM** [comment]
Is it possible to back rev obsidian to get notes working again? I depend on it and am not sure how quickly this will get fixed by Obsidian.

**Comment by I-Pch** [comment]
@OogieM : Obsidian v.0.15.1 has been released few hours ago 😊 ... I didn't had the time to test properly everything but this specific calendar bug seems to be fixed 😊

**Comment by liamcain** [comment]
The incompatibilities with v.0.15.0 should be fixed in the newest version of Obsidian. If not, please let me know.

**Comment by OogieM** [comment]
Not fixed as of Obsidian v.0.15.1 or at least I'm not seeing what I expect.  The pane (I'm using Sliding panes) where the notes open up seems random. It's not always the one that is currently open, sometimes it's the one before that. I haven't been able to replicate the set of things I do for when it fails so I'm not much help for debugging at the moment. But it's not every time and it very well could be a user error but it never did that before.

**Comment by I-Pch** [comment]
> I'm using Sliding panes

Sliding Panes might be the culprit here 🤔 ... Have you tried to disable it and use calendar to see if it works normally @OogieM ? 🤔 

I mean, the brand new "focus on side pane" feature which came with Obsidian 0.15+ seems to have impacted other plugins too (I just reported a bug with Templater and there's another one with Breadcrumbs)... and each time, it seems like the "buggy" plugins doesn't know where to do what needs to be done anymore (it doesn't know where to focus)... At least, this is how my non-dev' mind interpret the troubles I've encountered with Obsidian v.0.15+ 😇 .

But still, without using Sliding Panes and after the release of Obsidian v.0.15.1, Calendar seems to work as it used to 😊 .

**Comment by OogieM** [comment]
OK More info here. I'm using periodic notes. If I have 2 panes available and click in the right most pane then click on yesterdays date in the calendar in the right sidebar the note properly shows up in the rightmost pane. Then click in the leftmost pane and click to create the new note for today. The new note is created in the rightmost pane. Before this update it would create it in the left pane.

Once that happens even clicking in the left pane does not move the display slider so that I see the whole note. It's still set with the right note having the focus and the whole display. So not sliding ike they used to do. I have already sent theinfo to  the developer of Sliding Panes but tam reporting here sicne it may be a conflickt between the 2 plug-ins.
