### ISSUE TITLE
Add visualization for important dates

### ISSUE THREAD

**Issue by jokysatria** [liamcain/obsidian-calendar-plugin#33]
Hi, thank you so much for making this plugin, which makes joy when using the daily notes plugin.
I have a request (if it's possible), that is giving a mark/highlight to the calendar for daily notes which contain \#important tag?

Thanks again!

**Comment by mamoit** [comment]
Maybe instead of having `#important`, it should be configurable?
Because if I keep my notes in some other language than English it may not fit the flow.

If I can 1 up you idea, maybe even keep a key value list with "string" to color correspondence to keep different types of days.

I would probably keep this kind of information just in tags though, since it's not just important for days/months/years, but for any note that you may have.

**Comment by liamcain** [comment]
As of v1.4.5, if you use [frontmatter tags](https://publish.obsidian.md/help/Advanced+topics/YAML+front+matter), you can now use CSS to apply custom styling to the calendar. 

Because this is a lot less discoverable, I'll be doing a write-up of how to set this up (TBD), and be sharing common recipes in the [wiki](https://github.com/liamcain/obsidian-calendar-plugin/wiki).

**Comment by liamcain** [comment]
Okay, I did a first pass on the wiki content. I'm going to mark this issue as done and create a Discussion so that I can start getting early feedback on the wiki (what's clear/unclear) and the feature itself. @jokysatria, @mamoit, would love your thoughts on it though!

**Comment by mamoit** [comment]
The example is extremely nice!
Kudos.

**Comment by jokysatria** [comment]
Really like it, thank you very much @liamcain. For improvement, I just found that the star is not showed automatically in calendar when I put a tag. I need to refresh Obsidian first to see it. It'll be nice if automatically showed. But current feature is more than enough for my use case, thank you!

**Comment by liamcain** [comment]
@jokysatria , great to hear! 

> For improvement, I just found that the star is not showed automatically in calendar when I put a tag.

That's good feedback and luckily a simple fix. I'll make that automatic. A (bad UX) shortcut you can take is just click on a different day and click back since that triggers a refresh.

**Comment by jokysatria** [comment]
It works, thank you!
