### ISSUE TITLE
Allow disabling of words per dot

### ISSUE THREAD

**Issue by cmhelmr** [liamcain/obsidian-calendar-plugin#38]
Please allow a setting of "0" in words per dot to effectively disable the setting (hide all dots in the calendar). This would still allow the plugin to be used for task management (open dot for open tasks).

**Comment by liamcain** [comment]
Great idea. Sounds like a reasonable improvement. One current option for you would be setting the 'dots per word' to a very high number to effectively change the meaning from "How long is this note" to "does this note exist."

But I'll still add the `0` option regardless (since I might be dividing by zero in the code 🤔

**Comment by chadhelmer** [comment]
Great, thanks for the consideration. Yes I set the number extremely high but a dot always shows (even if there are no words in the note!). Setting 0 gives interesting results: it shows no dots for empty notes, and a lot of dots for notes with some words.

**Comment by cmhelmr** [comment]
Great, thanks for the consideration. Yes I set the number extremely high but a dot always shows (even if there are no words in the note!). Setting 0 gives interesting results: it shows no dots for empty notes, and a lot of dots for notes with some words.

**Comment by liamcain** [comment]
As of v1.4.0, setting the number of words per dot to `0` will disable it completely.
