### ISSUE TITLE
Option to make clicking Today button open today's daily note

### ISSUE THREAD

**Issue by jacklaing** [liamcain/obsidian-calendar-plugin#64]
I think clicking the Today button (between the arrows) should open today's Daily Note, but I recognize that not everyone will want that. Give us the option :)

**Comment by liamcain** [comment]
I'm always weary of giving users too much customization. I talked a bit about the design rationale for the "today" button here: https://github.com/liamcain/obsidian-calendar-plugin/issues/56#issuecomment-736525739

Is the main concern that the button's current behavior isn't intuitive? Or is it more so that you'd like a faster way to open today's daily note?

**Comment by jacklaing** [comment]
Coming from NotePlan, where the equivalent of clicking the Today button takes you to today's Daily Note, I often find myself instinctively clicking it then being disappointed.

At the moment the only function of the button is to bring you back to the current month if you're looking at a different month, which I don't do often. When I'm already in the current month, it does nothing. 

Perhaps there should be another layer to the logic of the button, where if you're already in the current month, rather than doing nothing, it opens the daily note.

**Comment by liamcain** [comment]
I see. It looks like NotePlan uses the same behavior as Fantastical: Clicking the month will go back to the current month. This was the original behavior for the plugin but I switched it since it was less discoverable. I do understand your concern about the button being more prominent than it needs to be. I'll keep this ticket open and give it more thought before I do any more UI updates.

Thanks for raising!

**Comment by cristianvasquez** [comment]
I always see the text 'Today' and I instinctively click it. 

Perhaps something in the middle, that: 
1. bring you back to the current month if you're looking at a different month,
2. open today's note, otherwise.

would work?

**Comment by liamcain** [comment]
I'm currently planning a slightly larger design update that should address this (+ #61) where you can quickly jump to other months/years. For the short term, I think I will revert back to the previous behavior: get rid of the "today" button and allow clicking the month name to return to the current month.

I'll convert this issue to a Discussion for now so that people can share there thoughts on this.
