### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by DutchPete** [liamcain/obsidian-calendar-plugin#66]
In the settings, what should be filled in in the "Weekly note template" box and in the "Weekly note folder"?

I had just put the name of the template I use and the name of the folder respectively, but the plug-in does not recognize that. So, in each box I put in more of the path, but still no luck.
Please advise.

**Comment by liamcain** [comment]
Hi @DutchPete, the 2 settings should work exactly the same way as the daily notes fields, with the exception that they don't have autocomplete (this is unfortunately missing from the API, see #44)

- **Template:** the path to the template file. Example: I use `templates/weekly`.
- **Folder:** name of the folder in your Obsidian vault for weekly notes. Double check that the folder exists before you use it, since the plugin won't create it for you.

Here are my settings for example:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/693981/101353013-f4cca400-3860-11eb-990d-e655cf0e5a60.png">

**Comment by DutchPete** [comment]
Liam, here are 2 screenshots: 1 showing my OS file explorer with the folder and template file, the other showing my calendar settings in Obs. 

At the bottom of the one of the file explorer you can see part of the path.

If my settings are right, then I am confused because when I click on the calendar week number say 51, for which there is no note yet, it says it cannot create the note.

<img width="431" alt="cal" src="https://user-images.githubusercontent.com/10794265/101355870-e487e980-389f-11eb-88b9-12673f776498.png">

<img width="844" alt="cal2" src="https://user-images.githubusercontent.com/10794265/101355935-02554e80-38a0-11eb-97c4-55a4bb8cf638.png">

**Comment by DutchPete** [comment]
Forgot to show my week note format.

<img width="844" alt="cal3" src="https://user-images.githubusercontent.com/10794265/101357205-cde29200-38a1-11eb-81a8-58f161f26408.png">

This should result for e.g. next week in Week-2020-51, right?

**Comment by liamcain** [comment]
Is "2020" the name of your vault? Or is it a folder within the vault?

I think you want "2020/Templates/Weekly-template" for your template path. Both paths should be relative to the root of your vault.

**Comment by DutchPete** [comment]
"2020" is the name of the vault, which is located in a folder called "Journal".

So, the template box now has this: Journal/2019-onward/2020/Templates/Week-template
And the note folder box has this: Journal/2019-onward/2020

"2019-onward" is just a folder, not a vault.

It still cannot create a new note. The odd thing is that, after our discussion about customization, I uninstalled and reinstalled the plug-in. It was working before the reinstallation and stopped after the reinstallation.

I am baffled.

**Comment by liamcain** [comment]
You don't need to include the vault name in the path. Sounds like you can keep the "folder" setting empty.

**Comment by DutchPete** [comment]
Yep, that works. Many thanks for your help, Liam. Cheers 👍
