### ISSUE TITLE
V1.4.5: 53 Week Years not Supported

### ISSUE THREAD

**Issue by jcrum** [liamcain/obsidian-calendar-plugin#75]
The Calendar widget shows 2020 with 52 weeks and the last week in December (27th -31st) as the first week in 2021; 2020 has 53 weeks. 

![Screen Shot 2020-12-14 at 2 09 00 PM](https://user-images.githubusercontent.com/527053/102146695-ee689a00-3e15-11eb-9bd6-242edafb6e39.png)

**Comment by liamcain** [comment]
I wish this was straightforward.

The week numbering is set according to your locale. So `en-US` uses the "Western traditional" calendar which means that January 1st always falls on the first week of the month (even though 2020 is a leap year). This is confusing since many applications (e.g. Google Calendar) will use ISO-8601 for week numbering.

I have found that Calendars are very split on what's the "standard" - Apple Calendar, for example, sticks with the Western traditional numbering, Fantastical uses ISO, etc. So, to compensate, I plan on exposing an option to override the locale that the calendar uses (tracked here #60)

**Comment by ericaxu** [comment]
I heard building calendars are hard... confirmed.

**Comment by zenodotus280** [comment]
#60 is rightfully marked closed; this one can also be closed.
